### ISSUE TITLE
[PE-D] user guide includes wrong examples for genre command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#154]
Expected: The genre example includes those genres in the genrelist
Actual: some uncovered genre occurred in example

![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/8f016d7b-cec7-4f01-8d43-67f56bd49810.png)

![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/d1bc225b-46a2-421e-8233-8dabb89999a8.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: qinguorui2001/ped#15

**Comment by auhc99** [comment]
nice
