### ISSUE TITLE
[PE-D] Episode of the anime is not displayed properly 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#156]
![Screenshot 2021-10-29 at 4.44.08 PM.png](https://raw.githubusercontent.com/ngchisern/ped/main/files/3efb3b35-38d8-446f-9d82-0a41c96111a4.png)
The episode is not shown entirely if the number is too large.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ngchisern/ped#4

**Comment by auhc99** [comment]
Mention in UG
