### ISSUE TITLE
[PE-D] The clear command will not show expected information

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#161]
At the to watch panel, clear the animes will not show the expected clear details
Expected: the details of clear info is shown
Actual: nothing is shown
![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/b365d6a1-a88c-4503-9d5b-7e588b6ea593.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: qinguorui2001/ped#16

**Comment by auhc99** [comment]
dup

**Comment by clyveycui** [comment]
#126
