### ISSUE TITLE
[PE-D] Possible simplification of UI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#162]
Since there are no file related commands, maybe it could be changed directly to the Exit command.

![image.png](https://raw.githubusercontent.com/AllardQuek/ped/main/files/83f98539-f442-4a99-bef0-b203278fadf0.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AllardQuek/ped#16

**Comment by auhc99** [comment]
ok will change
