### ISSUE TITLE
[PE-D] incorrect implementation of find

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#166]
When i type this command, it can work without invalid format warning
expected: warning
actual: nothing but works
![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/23d8c2c4-0601-4f58-8a47-da0b25a32ef8.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: qinguorui2001/ped#18

**Comment by auhc99** [comment]
will add error message

**Comment by clyveycui** [comment]
Add parameter checking, to ensure that only the correct parameters are provided
