### ISSUE TITLE
[PE-D] Possible relaxation of sci fi genre parsing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#171]
Some users might type 'scifi' or 'sci-fi' which would not be accepted.

![image.png](https://raw.githubusercontent.com/AllardQuek/ped/main/files/d911a796-4e64-4d5f-b014-a5fd4c1716f1.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: AllardQuek/ped#21

**Comment by auhc99** [comment]
Alias are not supported
