### ISSUE TITLE
[PE-D] Lag issue 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#173]
[Screen Recording 2021-10-29 at 5.18.02 PM.mov](https://raw.githubusercontent.com/ngchisern/ped/main/files/ad5b6622-f02c-45ed-84b8-a57db711ee09.mov)
Noticeable lag during tab switching if the user stores a large number of animes. 
Note: I tested with 50 animes only. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ngchisern/ped#7

**Comment by auhc99** [comment]
Use a better computer
