### ISSUE TITLE
[PE-D] Another inaccurate description of genre in glossary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#179]
In glossary, it said can only contain alphabets and ...  I think it's outdated since now only genres in genre list can be considered as genre, self-designed genre is not allowed. No need to say this requirement after stating the second sentence of GENRE in glossary. 
expected: remove this part
actual: it still exists there and it's unnecessary

![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/fb26bb03-764a-49f4-9c0b-8fb9e8700b83.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: qinguorui2001/ped#20

**Comment by auhc99** [comment]
Will update UG
