### ISSUE TITLE
[PE-D] Unclear images in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-4/tp#185]
This is the clearest image i can get from the user guide, even i enlarged the website still quite vague of some tags.
Expected: clear image
Actual: can't see details clearly even enlarge the page

![image.png](https://raw.githubusercontent.com/qinguorui2001/ped/main/files/78bd931c-adca-4473-a590-fc64ca94a4f6.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: qinguorui2001/ped#26

**Comment by clyveycui** [comment]
Hi, you might need an eye doctor. We can see it rather clearly in the screenshot.
