### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by clyveycui** [AY2122S1-CS2103T-T10-4/tp#9]
As a user, I can read more about the application, so that I can understand what I am using.

**Comment by NekrozQliphort** [comment]
- [ ] Add a UI mockup of our intended final product.
- [ ] Update all contents to match our own project.
- [ ] Update the link of the GitHub Actions build status badge so that it reflects the build status of our team repo.
- [ ] Acknowledge the original source of the code.
